sonar.projectKey=dilla-chat_dilla-chat
sonar.organization=dilla-chat

sonar.sources=client/src,server-rs/src
sonar.tests=client/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.coverage.exclusions=**/*.test.{ts,tsx},client/src/test/**
sonar.cpd.exclusions=**/*.test.{ts,tsx},**/test/**,**/mock*

sonar.exclusions=client/public/**,docs/**

sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e4.ruleKey=shellcheck:S1192
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.sh
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S7781
sonar.issue.ignore.multicriteria.e3.resourceKey=**/telemetry.ts
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S4123
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.test.{ts,tsx}
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S2245
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.test.{ts,tsx},**/test/**,**/mock*
