use axum::{
    extract::{Path, State},
    http::{HeaderMap, StatusCode},
    response::{IntoResponse, Response},
    Extension, Json,
};
use rust_embed::Embed;
use serde_json::{json, Value};

use crate::api::AppState;
use crate::auth::UserId;
use crate::error::AppError;

/// Embedded voice model artifacts.
///
/// At compile time the `assets/voice-models/` folder (relative to the crate
/// root) is baked into the binary. The `manifest.json` file is generated by
/// `build.rs` from the SHA-256 of the three DFN3 sub-graphs and is the
/// source of truth the client uses to validate downloads.
#[derive(Embed)]
#[folder = "assets/voice-models/"]
#[allow(dead_code)]
struct VoiceModels;

/// Whitelist of model file sub-paths the server is allowed to serve.
///
/// The DFN3 model ships as three ONNX sub-graphs in a versioned subdirectory.
/// Anything not in this list returns 404 to prevent path traversal attacks.
const ALLOWED_MODEL_PATHS: &[&str] = &[
    "dfn3-v2/enc.onnx",
    "dfn3-v2/erb_dec.onnx",
    "dfn3-v2/df_dec.onnx",
];

pub async fn models_manifest() -> Response {
    match VoiceModels::get("manifest.json") {
        Some(file) => {
            let mut headers = HeaderMap::new();
            headers.insert("content-type", "application/json".parse().unwrap());
            headers.insert("cache-control", "public, max-age=300".parse().unwrap());
            headers.insert(
                "cross-origin-resource-policy",
                "same-origin".parse().unwrap(),
            );
            (StatusCode::OK, headers, file.data.into_owned()).into_response()
        }
        None => (
            StatusCode::NOT_FOUND,
            "voice model manifest not built — rebuild server with assets/voice-models/ populated",
        )
            .into_response(),
    }
}

pub async fn models_serve(Path(path): Path<String>) -> Response {
    // Whitelist exact known sub-paths to prevent traversal and unwanted serving.
    if !ALLOWED_MODEL_PATHS.contains(&path.as_str()) {
        return (StatusCode::NOT_FOUND, "").into_response();
    }
    match VoiceModels::get(&path) {
        Some(file) => {
            let mut headers = HeaderMap::new();
            headers.insert("content-type", "application/octet-stream".parse().unwrap());
            headers.insert(
                "cache-control",
                "public, max-age=31536000, immutable".parse().unwrap(),
            );
            // Required by COEP=require-corp on the webapp routes.
            headers.insert(
                "cross-origin-resource-policy",
                "same-origin".parse().unwrap(),
            );
            (StatusCode::OK, headers, file.data.into_owned()).into_response()
        }
        None => (StatusCode::NOT_FOUND, "").into_response(),
    }
}

pub async fn get_room(
    Extension(UserId(_user_id)): Extension<UserId>,
    State(_state): State<AppState>,
    Path((_team_id, _channel_id)): Path<(String, String)>,
) -> Result<Json<Value>, AppError> {
    // Stub: voice rooms are managed via WebSocket signaling.
    Ok(Json(json!({
        "participants": [],
    })))
}
