// Re-export from split modules for backward compatibility — named exports only
export {
  encoder,
  concatBytes,
  randomBytes,
  toBase64,
  fromBase64,
  type Ed25519KeyPair,
  generateEd25519KeyPair,
  ed25519Sign,
  ed25519Verify,
  importEd25519PublicKey,
  exportEd25519PrivateKey,
  importEd25519PrivateKey,
  type X25519KeyPair,
  generateX25519KeyPair,
  x25519DH,
  exportX25519PrivateKey,
  importX25519PrivateKey,
  aesGcmEncrypt,
  aesGcmDecrypt,
  hkdfDerive,
  type PrekeyBundle,
  generatePrekeyBundle,
  x3dhInitiate,
  x3dhRespond,
  RatchetSession,
  GroupSession,
  generateSafetyNumber,
  CryptoManager,
  passphraseToKey,
  encryptSessionData,
  decryptSessionData,
} from './crypto/index';
